# Generated by Django 3.1.3 on 2020-11-28 10:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listitem',
            managers=[
                ('listItem', django.db.models.manager.Manager()),
            ],
        ),
    ]
